
// Objective-C API for talking to the following Go packages
//
//	github.com/EpiK-Protocol/epik-wallet-golib/epik
//	github.com/EpiK-Protocol/epik-wallet-golib/hd
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Epik_FRAMEWORK_H__
#define __Epik_FRAMEWORK_H__

#include "EPIK_Epik.objc.h"
#include "EPIK_Hd.objc.h"
#include "Universe.objc.h"

#endif
