// Objective-C API for talking to github.com/EpiK-Protocol/epik-wallet-golib/epik Go package.
//   gobind -lang=objc -prefix="EPIK_" github.com/EpiK-Protocol/epik-wallet-golib/epik
//
// File is generated by gobind. Do not edit.

#ifndef __EPIK_Epik_H__
#define __EPIK_Epik_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EPIK_EpikEPKMessage;
@class EPIK_EpikPrivateKey;
@class EPIK_EpikWallet;

/**
 * EPKMessage ...
 */
@interface EPIK_EpikEPKMessage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t version;
@property (nonatomic) NSString* _Nonnull from;
@property (nonatomic) NSString* _Nonnull to;
@property (nonatomic) NSString* _Nonnull value;
@property (nonatomic) int64_t nonce;
@property (nonatomic) int64_t gasLimit;
@property (nonatomic) NSString* _Nonnull gasPrice;
@property (nonatomic) NSString* _Nonnull method;
@property (nonatomic) NSData* _Nullable params;
@end

/**
 * PrivateKey ...
 */
@interface EPIK_EpikPrivateKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull keyType;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

/**
 * Wallet wallet
 */
@interface EPIK_EpikWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewWallet ...
 */
- (nullable instancetype)init;
// skipped method Wallet.AddrList with unsupported parameter or return types

/**
 * Balance ...
 */
- (NSString* _Nonnull)balance:(NSString* _Nullable)addr error:(NSError* _Nullable* _Nullable)error;
/**
 * Export ...
 */
- (EPIK_EpikPrivateKey* _Nullable)export:(NSString* _Nullable)addr error:(NSError* _Nullable* _Nullable)error;
/**
 * GenerateKey t:bls,secp256k1
 */
- (NSString* _Nonnull)generateKey:(NSString* _Nullable)t seed:(NSData* _Nullable)seed error:(NSError* _Nullable* _Nullable)error;
/**
 * HasAddr ...
 */
- (BOOL)hasAddr:(NSString* _Nullable)addr;
/**
 * Import ...
 */
- (NSString* _Nonnull)import:(EPIK_EpikPrivateKey* _Nullable)privateKey error:(NSError* _Nullable* _Nullable)error;
/**
 * MessageList ...
 */
- (NSString* _Nonnull)messageList:(int64_t)toHeight addr:(NSString* _Nullable)addr error:(NSError* _Nullable* _Nullable)error;
/**
 * Send ...
 */
- (NSString* _Nonnull)send:(NSString* _Nullable)to amount:(NSString* _Nullable)amount error:(NSError* _Nullable* _Nullable)error;
/**
 * SetDefault ...
 */
- (BOOL)setDefault:(NSString* _Nullable)addr error:(NSError* _Nullable* _Nullable)error;
/**
 * SetRPC ...
 */
- (BOOL)setRPC:(NSString* _Nullable)url token:(NSString* _Nullable)token error:(NSError* _Nullable* _Nullable)error;
/**
 * Sign ...
 */
- (NSData* _Nullable)sign:(NSString* _Nullable)addr hash:(NSData* _Nullable)hash error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewWallet ...
 */
FOUNDATION_EXPORT EPIK_EpikWallet* _Nullable EPIK_EpikNewWallet(NSError* _Nullable* _Nullable error);

#endif
